services:
  - type: web
    name: glass-type-predictor
    env: python
    buildCommand: python -m pip install gunicorn && python -m pip install -r requirements.txt
    startCommand: python -m gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 